@FreeStays.API_HostAddress = http://localhost:5240
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMxNTA4ZTE5LWU0ZGItNDQ4Yy1hMzRhLTNkMWNjOWMyMjQ5NiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImJpbGdpQHRleWJpbGlzaW0uY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkhhbGl0IFlJTE1BWiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlN1cGVyQWRtaW4iLCJsb2NhbGUiOiJ0ciIsImV4cCI6MTc2NjAwMTMwNiwiaXNzIjoiRnJlZVN0YXlzLkFQSS5EZXZlbG9wbWVudCIsImF1ZCI6IkZyZWVTdGF5cy5DbGllbnQuRGV2ZWxvcG1lbnQifQ._wl-k2f-P4ZYdYKa848TtUKT4qzm9ADH2Q-guVi-_Ow

###
# Login
POST {{FreeStays.API_HostAddress}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "bilgi@teybilisim.com",
  "password": "Admin123!"
}

###
# Dashboard
GET {{FreeStays.API_HostAddress}}/api/v1/admin/dashboard
Accept: application/json
Authorization: Bearer {{token}}

###
# Get Customers
GET {{FreeStays.API_HostAddress}}/api/v1/admin/customers
Accept: application/json
Authorization: Bearer {{token}}

###
