### Test Public Hotels API Endpoints
@baseUrl = https://localhost:7001/api/v1/public

### 1. Get Featured Hotels (All stars)
GET {{baseUrl}}/featured-hotels
Accept-Language: tr
###

### 2. Get Featured Hotels (5 stars only)
GET {{baseUrl}}/featured-hotels?stars=5&count=5
Accept-Language: en
###

### 3. Get Featured Hotels (4 stars, Turkish)
GET {{baseUrl}}/featured-hotels?stars=4&count=8
Accept-Language: tr
###

### 4. Get Popular Destinations (All countries)
GET {{baseUrl}}/popular-destinations
Accept-Language: tr
###

### 5. Get Popular Destinations (Turkey only)
GET {{baseUrl}}/popular-destinations?country=TR&count=5
Accept-Language: tr
###

### 6. Get Popular Destinations (English language)
GET {{baseUrl}}/popular-destinations?count=15
Accept-Language: en
###

### 7. Get Romantic Hotels
GET {{baseUrl}}/romantic-hotels
Accept-Language: tr
###

### 8. Get Romantic Hotels (More results)
GET {{baseUrl}}/romantic-hotels?count=20
Accept-Language: en
###

### 9. Get Accommodation Types (Themes and Features)
GET {{baseUrl}}/accommodation-types
Accept-Language: tr
###

### 10. Get Accommodation Types (English)
GET {{baseUrl}}/accommodation-types
Accept-Language: en
###

### 11. Get Accommodation Types (German)
GET {{baseUrl}}/accommodation-types
Accept-Language: de
###

### 12. Featured Hotels with French language
GET {{baseUrl}}/featured-hotels?stars=5&count=10
Accept-Language: fr
###
